doc.cpp
The triggered line is critical information when determining failure root cause.
(I haven't actually tested this (testing requires the Windows VM compilation rigamarole) but it seems simple enough.)
=> document the triggered line in error messages

paneline.cpp
This fixes a problem I'm having with being unable to capture style runs that are supposed to bleed across lines.
See https://mushclient.com/forum/?id=13892&reply=3#reply3
=> without empty styles, we never catch colored EOLs

MUSHclient.cpp, MUSHclient.rc, MUSHclient.vcxproj, appveyor.yml, doc.h, version.h
Version info should only be in one spot
Also forward an environment variable defined in the appveyor file to check instead of looking at the version of the compiler. Otherwise you can't update your compiler ever.
=> make new versions easier

stdafx.h
This shrinks the MSVC2015 exe size by about 2MB. Not yet VC6 size, but much closer.
https://blogs.msdn.microsoft.com/vcblog/2012/02/06/reducing-the-size-of-statically-linked-mfc-applications-in-vc11/
=> reduce mfc exe size with this one weird trick

lua/movewindow.lua
This can cause problems when alternating between windows/displays of different sizes. If a user switches from a large window to a small one, the miniwindows may auto-position themselves at launch to keep them on screen. But when the user goes back to a large screen, they should get their original positions back, not be forced into their auto-position setting. Likewise, save specified location instead of auto location.
=> never clobber specified mode/flags or position

ansi.cpp, stdafx.h
Modified stadfx.h and ansi.cpp to support SGR 9 and 29, ANSI strikethrough and cancel strikethrough
Does exactly what it says on the tin. MUSHclient 5.03 added support for strikethrough styling on notes, this expands that to recognize strikethrough styling on received text.
=> Added ANSI strikethrough support

scripting/methods/methods_clipboard.cpp
This is the minimum change needed for the CopyColourCodes plugin to be able to get utf8 lines
=> make SetClipboard follow the utf8 setting too

ansi.cpp, doc.cpp, doc.h
This is an implementation of 24-bit color ANSI escape sequences (`38/48;2`). The primary functionality is built into `CMUSHclientDoc::Interpret256ANSIcode` (escape code `38/48;5`) due to the similarity in handling.
**See:** [Forum Thread](http://www.gammon.com.au/forum/?id=14381)
Comment for cleanup if necessary, though I did try to keep the commit as trim as possible.
**Please inspect** for any issues I may not be aware of, as I am not familiar with the entirety of the codebase.
Regards,
zinmirai
=> ANSI 24-bit color support

mushview.cpp
I don't know why SetScrollInfo doesn't work right, but without this change, hiding the scroll bar and then scrolling causes the bar to flicker repeatedly, which causes the world to resize repeatedly for no reason, which causes OnPluginWorldOutputResized to get called repeatedly for no reason.
http://mushclient.com/forum/bbshowpost.php?bbsubject_id=14581&page=1
=> Use SetScrollPos not SetScrollInfo to prevent flickering during scroll

lua/movewindow.lua
Always doing the reposition leads to unfriendly jumps away from the new desired location if WindowPosition is called shortly after creating the window.
=> Don't reposition during check unless out of bounds

plugins/Text_To_Speech.xml
The original microsoft download link for SpeechSDK51.exe is defunct.
=> Update the SpeechSDK download URL to archive.org

lua/movewindow.lua
Overwriting miniwindow_flags during move disrupts any custom flags that were set on the miniwindow like miniwin.create_transparent. Currently a transparent window once moved stops being transparent.
=> Don't change miniwindow flags during move

scripting/methods/methods_miniwindows.cpp
It seems like this mousemove check for newly created hotspots shouldn't happen if the user is already dragging another hotspot around.
=> Proposed fix for addhotspot error while dragging

scripting/lua_methods.cpp
We don't stricly need these fields to be strings and it fixes a funny third party backwards compatibility issue on my end.
=> Treat nil as "" for ColourTell and ColourNote color fields

dialogs/plugins/PluginsDlg.cpp
Having something selected by default causes accidents. Someone accidentally double-clicked the Remove button and caused too many plugins to get removed.
=> Don't select any plugin by default.

install/mushclient.nsi
Based on the best practices  for developing apps for windows, the Registry Key for publisher should be set.
Additional work should be completed to also set the DisplayVersion registry entry based on the version of the application
=> Add publisher entry to Control Panel

dialogs/plugins/PluginsDlg.cpp
Wine and Windows behavior diverges here slightly. In Wine items in the plugin dialog can be selected by first letter without this change, but in Windows apparently that is not the case. We still don't want to select anything though to prevent double removals like the previous edit here.
=> Re-add dialog focus, just without selection

lua/movewindow.lua
I am not sure if this is the proper solution as I don't even remotely have explored all plugins importing movewindow.lua but it seems to me that we should be defaulting to 2 instead of 0.
=> Fixes #79 Broken fresh installations of Learning_Mapper.lua plugin and derivatives

lua/wait.lua
I often find myself (and see others) writing plugin functions similar to the following somewhat simplified example:
```
function countdown_alias(name, line, wildcards)
local count = tonumber(wildcards.count) or 3
wait.make(function()
while count >= 0 do
Note(count)
wait.time(1)
count = count - 1
end
end)
end
```
This is currently the best way to use `wait.make()` for such a need, but there are some problems:
- The `countdown_alias()` function contains too many levels of indentation and is arguably harder to read than needs be for such a simple case.
- The coroutine that actually does the counting down is anonymous and therefore not reusable anywhere else in the script.
- The coroutine also depends on the `count` upvalue, so it can't be factored out into a named function without making …
=> Allow `make()` to pass arbitrary arguments to coroutines

telnet_phases.cpp
... as some MUDs might not send it 24-bit RGB colors due to MushClient not advertising its support of it via MTTS.
But it supports 24-bit colors since around c89d236.
So, advertise its support for it.
=> MTTS: mark MushClient as supporting TRUECOLOR codes

MUSHclient.vcxproj
I got a report that a4e6a429c8d4ffdca43644efe85dbe120ed7c464 causes an assertion failure in the CTime constructor with Wine on a user's M4 Mac, so I guess let's undo it. 🤷
=> Test removing the 32 bit time macro

.github/workflows/latest-dev-build.yml
I think this does it?
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
=> De-collide workflow runs
